resources:
  - rollout.yaml
  - service-stable.yaml
  - service-canary.yaml
  - analysis-template-newman.yaml
  - analysis-template-prometheus.yaml
  - rbac-analysis-job.yaml
  - scaledobject.yaml
configurations:
  - kustomize-config.yaml
