apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-be-api-logs-pvc
  namespace: default
  labels:
    app: test-be-api-logs-pvc
    managed-by: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi